### ISSUE TITLE
Tkinter error when trying to add part

### ISSUE THREAD

**Issue by jclane** [jclane/SubHunt#52]
## Expected Behavior
It shouldn't be throwing an error.

## Current Behavior
Getting the following error when trying to add a part.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Users\jclane\Desktop\SubHunt - Copy\frontend.py", line 555, in add_it
    self.clear_fields()
  File "C:\Users\jclane\Desktop\SubHunt - Copy\frontend.py", line 507, in clear_fields
    print(entry.get())
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 3040, in get
    return self.tk.call(self._w, 'get')
_tkinter.TclError: invalid command name ".!frame.!addpartpage.!frame2.!frame2.!entry"
```

## Possible Solution
Stack trace seems to indicate problem is on line 551 of frontend.py so I'll start there.

## Steps to Reproduce
1.  Go to the add part screen.
2.  Add an HDD.
3.  Go to add a SSD now.
4.  Click add button and see error.

**Comment by jclane** [comment]
I think `clear_fields` it's trying to delete an entry box that no longer exists.  Seems when part type is changed all of the widgets are destroyed and `clear_fields` is trying to clear one of those widgets.
